### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by subins2000** [NaikSoftware/PHPRunner#1]
It would be better if the project had a documentation about how to cross compile PHP and it's dependencies.

**Comment by NaikSoftware** [comment]
@subins2000 I use pre-compiled PHP from other program

**Comment by subins2000** [comment]
@NaikSoftware May I know where you got it from ?

**Comment by NaikSoftware** [comment]
See other server apps in Google Play

**Comment by subins2000** [comment]
@NaikSoftware Yup, got it
